### ISSUE TITLE
[a2] model.states

### ISSUE THREAD

**Issue by ranjeetkumar** [iit-cs585/assignments#10]
Hi Professor/TA,
In the assignment a2, it is not mentioned explicitly where to create instance variable states and it is being used in the main function. We can do in any function expect viterbi of HMM class?
Thanks,
Ranjeet

**Comment by aronwc** [comment]
Yes - I'd recommend initializing the states variable in the fit_transition_probas function. This should be a sorted list of strings, one per state in the model.

**Comment by ranjeetkumar** [comment]
Thanks a lot
