### ISSUE TITLE
[a2] output

### ISSUE THREAD

**Issue by ranjeetkumar** [iit-cs585/assignments#11]
Hi Professor/TA,
When I ran a2.py, I got 34 models. In a2.py file there are 33 models
Answer from a2.py file:
$ python3 a2.py  
	model has 33 states
	['$', "''", ',', ':', 'CC', 'CD', 'DT', 'EX', 'IN', 'JJ', 'JJR', 'JJS', 'MD', 'NN', 'NNP', 'NNPS', 'NNS', 'POS', 'PRP', 'PRP$', 'RB', 'RBR', 'TO', 'VB', 'VBD', 'VBG', 'VBN', 'VBP', 'VBZ', 'WDT', 'WP', 'WRB', '``']
	predicted parts of speech for the sentence ['Look', 'at', 'what', 'happened']
	(['VB', 'IN', 'WP', 'VBD'], 2.752640843234699e-10)

My output:
model has 34 states
['$', "''", ',', '.', ':', 'CC', 'CD', 'DT', 'EX', 'IN', 'JJ', 'JJR', 'JJS', 'MD', 'NN', 'NNP', 'NNPS', 'NNS', 'POS', 'PRP', 'PRP$', 'RB', 'RBR', 'TO', 'VB', 'VBD', 'VBG', 'VBN', 'VBP', 'VBZ', 'WDT', 'WP', 'WRB', '``']
predicted parts of speech for the sentence ['Look', 'at', 'what', 'happened']
(['VB', 'IN', 'WP', 'VBD'], 2.751820088075314e-10)

I have this  **'.'** as extra. I look into the data then I see that is present

snapshot from data.txt
provide VB
structural JJ
parts NNS
for IN
Boeing NNP
's POS
747 CD
jetliners NNS
. .

Rockwell NNP
said VBD

Do we have to ignore that? I am only considering newline to separate out different sentences.

**Comment by aronwc** [comment]
You're right - '.' should be a state. I'll update soon.

**Comment by ranjeetkumar** [comment]
Thanks a lot
