### ISSUE TITLE
[a2] minor verification

### ISSUE THREAD

**Issue by ranjeetkumar** [iit-cs585/assignments#12]
Hi Professor/TA,
1) In lecture 8, formula for smoothing transition probablity is written as 
![image](https://cloud.githubusercontent.com/assets/1698169/22621746/c725f760-eb50-11e6-99dd-8015b2b367b4.png)

  In numerator also, it will be k instead of 1?

2) In viterbi algorithm,
![nlp2](https://cloud.githubusercontent.com/assets/1698169/22621729/74ae0ec8-eb50-11e6-86f2-311e53f84faa.PNG)

a <sub>s,q<sub>F</sub></sub> implied value is  1 in our assignment?

**Comment by aronwc** [comment]
Yes, k=1 in that example.

**Comment by ranjeetkumar** [comment]
Thanks a lot.
