### ISSUE TITLE
a2:  viterbi Algorithm: Hard to Understand

### ISSUE THREAD

**Issue by changediyasunny** [iit-cs585/assignments#15]
Hi Prof,
I have couple of doubts implementing viterbi algorithm:
1. What is the sequence of states  **S'** in `viterbi[s,t]←N max s'=1 {viterbi[s',t −1] ∗ a[s',s] ∗ bs(O[t])}`

2. How to calculate viterbi[qf, t] ? `viterbi[qF ,T]←N max s'=1 viterbi[s,T] ∗ a[s,qF]`
How to take final state ?
`
This algorithm is getting heavy and very confusing.

**Comment by aronwc** [comment]
s' is a single state. This definition is specifying how at time t we must
consider all possible prior states when computing the max.

For the final state, we just compute the max over the final states in the
sequence. Note that in this assignment, you do not need to add artificial
"end states."

-Aron

**Comment by changediyasunny** [comment]
alright. thank you Prof.
