### ISSUE TITLE
Smoothing for Initial Probabilities

### ISSUE THREAD

**Issue by Tsreenivasan** [iit-cs585/assignments#16]
Hi All,

Would we be using the Laplacian k-smoothing for the initial probabilities as well?

Example:
k=.001
test_tags = [
            ['D', 'N', 'V'],
            ['D', 'N', 'V'],
            ['V', 'N'],
            ['D', 'N', 'N', 'V']
        ]
|V|={D,N,V}

Would the calculation for the start probability be:
![image](https://cloud.githubusercontent.com/assets/11288412/23143986/30963800-f78a-11e6-9665-d8c6e508e732.png)

P(Start=D)=> (3+.01)/(4+3*.01)

Can anyone confirm?

Regards
Tejas

**Comment by ranjeetkumar** [comment]
Start probability for D is correct

**Comment by Tsreenivasan** [comment]
Thanks Ranjeet.
