### ISSUE TITLE
a2 Output: mismatch in probability (POS tags are right !)

### ISSUE THREAD

**Issue by theTechie** [iit-cs585/assignments#17]
Hi,

My final path probability is off by a large difference ~ 7.3e-10 

Is this acceptable considering the variations based on different environments 
OR 
am i certainly wrong somewhere ?

---------------
model has 34 states
['$', "''", ',', '.', ':', 'CC', 'CD', 'DT', 'EX', 'IN', 'JJ', 'JJR', 'JJS', 'MD', 'NN', 'NNP', 'NNPS', 'NNS', 'POS', 'PRP', 'PRP$', 'RB', 'RBR', 'TO', 'VB', 'VBD', 'VBG', 'VBN', 'VBP', 'VBZ', 'WDT', 'WP', 'WRB', '``']
predicted parts of speech for the sentence ['Look', 'at', 'what', 'happened']

**(['VB', 'IN', 'WP', 'VBD'], 9.301823359846707e-10)**

**Comment by aronwc** [comment]
To this and similar questions: it's impossible for me to tell whether the difference is due to different computing environments or difference in implementation. Please try your best to confirm your implementation based on the tests and examples provided in class.

**Comment by theTechie** [comment]
Sounds good. I have tried multiple examples manually computing probabilities inline with my implementation. All values sum up right. 

All tests pass too.
