### ISSUE TITLE
Question about HMM transition probability

### ISSUE THREAD

**Issue by ZihanNiu** [iit-cs585/assignments#19]
Hi Prof,
Although we discussed this quiz problem in class, I still feel confused. In Quiz2 we were asked to estimate P(V|N) and we do model the end states. So I think the formula is :
![screen shot 2017-02-28 at 7 22 23 pm](https://cloud.githubusercontent.com/assets/11018996/23441952/4e5e794e-fdeb-11e6-82e0-df11dbf18039.png)
And we plugged in number:
![screen shot 2017-02-28 at 7 24 55 pm](https://cloud.githubusercontent.com/assets/11018996/23442015/9d0a4f1e-fdeb-11e6-9f5d-25c09f47ac94.png)
I think N is the number of part of speech tags, (D,A,N,V) =4, why is 5 in this case? And what if we also model start states, will N become 6?

**Comment by aronwc** [comment]
It is 5 because we need to consider the transition N->`</s>`

One useful exercise: try computing all of P(V|N), P(D|N), ..., P(`</s>`|N) and make sure they add to one.
