### ISSUE TITLE
doubt in test_read_grammar

### ISSUE THREAD

**Issue by mychandru024** [iit-cs585/assignments#2]
Respected Professor,

in the test case test_read_grammar there are two set of assertTrue statements checking for different values both times at the same index of the list of tuples. I am wondering how this works?

Thank you

**Comment by aronwc** [comment]
That would be strange, wouldn't it!

No, this is a bug. I've updated the test and pushed the change to the assignments repo.
Here is the [diff](https://github.com/iit-cs585/assignments/commit/d87f1fd69eab03d13dea1b6c89ec09b19c0f38d0#diff-61b2a26293ff06da7fece2b12c92e471)
