### ISSUE TITLE
n_params

### ISSUE THREAD

**Issue by yfan000** [iit-cs585/assignments#21]
Hi guys,

What does "the total number of parameters in the resulting classifier" mean in evaluate_combinations?

combination results:
          f1  **n_params**   caps    pos  chunk context
13  0.693375     91225   True   True  False    True
15  0.693336     91450   True   True   True    True
11  0.678049     90790   True  False   True    True
9   0.674556     90565   True  False  False    True
5   0.639389     91210  False   True  False    True
8   0.637879     30920   True  False  False   False
7   0.637036     91435  False   True   True    True
10  0.635057     30995   True  False   True   False
14  0.605595     31215   True   True   True   False
12  0.604120     31140   True   True  False   False
6   0.562795     31210  False   True   True   False
4   0.558451     31135  False   True  False   False
3   0.503278     90775  False  False   True    True
1   0.467874     90550  False  False  False    True
2   0.367361     30990  False  False   True   False
0   0.330491     30915  False  False  False   False

**Comment by ranjeetkumar** [comment]
It the count of all the coefficients(thetas) of the classifier.

**Comment by yfan000** [comment]
Thanks! Problem solved.
