### ISSUE TITLE
Values in the confusion matrix in the log file

### ISSUE THREAD

**Issue by prateekagrawal06** [iit-cs585/assignments#22]
Hi Professor,

In assignment a3.

The function where we create a confusion matrix tell that the rows should correspond to the true values and the column should correspond to the predicted values. 

But the values in the confusion matrix in the log file is different. The values are written as if the rows are corresponding to the predicted values and the columns are corresponding to the true values.

Please correct me if I have understood it wrong.

**Comment by ranjeetkumar** [comment]
>>The function where we create a confusion matrix tell that the rows should correspond to the true values and the column should correspond to the predicted values.

Little bit of misunderstanding: See below
The function where we create a confusion matrix tell that the rows should correspond to the true **label(class)** and the column should correspond to the predicted **label(class).**

To clarify, row is true label and column is predicted label. If we consider one complete row values for any particular class then it is predicted values of that class for each label in the column. Similarly, column values mean how many it correctly predicted for each class for particular column label.

 Assuming a sample of 27 animals — 8 cats, 6 dogs, and 13 rabbits, the resulting confusion matrix could look like the table below:
![confusion](https://cloud.githubusercontent.com/assets/1698169/23887560/b7b1ce92-08a8-11e7-9226-c7354dba9dfe.PNG)

In this confusion matrix, of the 8 actual cats, the system predicted that three were dogs, and of the six dogs, it predicted that one was a rabbit and two were cats
https://en.wikipedia.org/wiki/Confusion_matrix

**Comment by prateekagrawal06** [comment]
Hi Ranjeet,

Thanks a lot for the clarification.
