### ISSUE TITLE
A3:  training data shape is 27858. what is missing ? 

### ISSUE THREAD

**Issue by changediyasunny** [iit-cs585/assignments#23]
Hey Guys,
I rechecked again all parameters and found to have same features shape as mentioned in the previous issues.
what is missing to get 27867 ?

total labels: 27858
training data shape: (27858, 18726)

feature_list[:3] = 
[
{'is_caps': 1, 'chunk=I-NP': 1, 'tok=eu': 1, 'next_pos=VBZ': 1, 'next_chunk=I-VP': 1, 'next_tok=rejects': 1, 'pos=NNP': 1},
{'pos=VBZ': 1, 'prev_tok=eu': 1, 'next_tok=german': 1, 'tok=rejects': 1, 'next_pos=JJ': 1, 'next_chunk=I-NP': 1, 'next_is_caps': 1, 'prev_chunk=I-NP': 1, 'prev_is_caps': 1, 'prev_pos=NNP': 1, 'chunk=I-VP': 1},
{'next_pos=NN': 1, 'is_caps': 1, 'next_chunk=I-NP': 1, 'tok=german': 1, 'chunk=I-NP': 1, 'prev_chunk=I-VP': 1, 'pos=JJ': 1, 'prev_pos=VBZ': 1, 'next_tok=call': 1, 'prev_tok=rejects': 1}

]

Regards,
Sunny

**Comment by ranjeetkumar** [comment]
You missed the last sentence. I too initially missed that.

**Comment by changediyasunny** [comment]
thanks @ranjeetkumar . I got it. fishy bug in the code. never observed.

**Comment by changediyasunny** [comment]
@ranjeetkumar  I get correct length of feature dict but shape seems to be weird.

training data shape: (27867, **18729**)
my feature list is as shown above. I don't think any feature is missing.  any suggestion ?

**Comment by ranjeetkumar** [comment]
I think you are crossing sentence boundaries for context features
See this
https://github.com/iit-cs585/assignments/issues/20#issuecomment-286224338

**Comment by changediyasunny** [comment]
@ranjeetkumar  yes. I am crossing that. It's kind of vague, as function description does not mention about that explicitly.
