### ISSUE TITLE
Instruction Query for A3

### ISSUE THREAD

**Issue by Tsreenivasan** [iit-cs585/assignments#26]
Hi Professor @aronwc,

there was an instruction mentioning not to use external libraries for the evolution matrix calculation. does that imply we shouldn't to use Pandas features [iterrows, iteritems() and sum()] in P,R,F1 calculations?

Regards
Tejas

**Comment by aronwc** [comment]
you can use those functions.

**Comment by Tsreenivasan** [comment]
Thanks Professor
