### ISSUE TITLE
Using logistics function as activation in each RNN cell

### ISSUE THREAD

**Issue by prateekagrawal06** [iit-cs585/assignments#30]
Hi Professor,

The Assignment 4 bonus part tells that we need to use logistic as the activation function for each cell in the hidden layer. Does this mean that we need to change the tanh activation to sigmoid in the BASICRnnCell implementation of tensorflow?

**Comment by aronwc** [comment]
That would be one way to do it.

**Comment by prateekagrawal06** [comment]
Thanks, professor
