### ISSUE TITLE
<Project>: Not enough memory: Generating Parse Tree from list of sentence

### ISSUE THREAD

**Issue by changediyasunny** [iit-cs585/assignments#32]
Hi Prof. @aronwc  ,

I tried both ways of generating parse trees using single sentence at a time and list of sentences at a time to stanford-Dependancy parser. 
In both implementations, I get "not enough memory " error after processing 89 sentences. I tried searching for better ways to utilize memory for parse tree generation but couldn't find anything helpful other than above mentioned methods

sometimes, it is also noted that sentence length is a limiting factor while creating parse tree. 
Eg. if list_of_sentence is passed to parser, max_length should be 100/120 words otherwise, it throws "java: memory error".

any suggestions ? My raw data generally have long text with meaningful information. long reviews tend to be more sensible and meaningful.

**Comment by aronwc** [comment]
After you generate each parse tree, you should write it to disk, making sure it is no longer in memory. You may also try limiting sentences to < 100 words.

**Comment by changediyasunny** [comment]
Hi Prof. @aronwc ,
Well, i am iterating over 50 reviews (length < 100) at a time and saving back result to file. 
 After doing that, it takes a while to generate all parse trees.  
The reviews with string " 2 1/2-hour" {number number/number text} format throws assertions error and there is still a bug (stanford core nlp github)  in pending for an action.
Suggest ?
