### ISSUE TITLE
a4(part 2)

### ISSUE THREAD

**Issue by ranjeetkumar** [iit-cs585/assignments#33]
How we feed data to RNN? In our assignment after vectorization, we have two dimension matrix as input. Suppose, we have a matrix with shape (m,n), how we will feed this input to the RNN? How to decide the batch size, no of batches, series length etc? Can anyone please explain?

**Comment by aronwc** [comment]
I'm a little confused by your question.
The input is (m,n), but this is for all tokens in a sentence. Each single
token has a vector representation. See, e.g., in L19, how we created a
vector for each token in the `train_all` method.

```python
inputs = [char_to_ix[ch] for ch in data.lower()[p:p+seq_length]]
```

You might also look at  the `ptb_producer` method from the tensor flow
tutorial for example:
https://github.com/tensorflow/models/blob/master/tutorials/rnn/ptb/reader.py

This is used to create the input data structure for the RNN
https://github.com/tensorflow/models/blob/master/tutorials/rnn/ptb/ptb_word_lm.py

-Aron

**Comment by karthikshivaram24** [comment]
Professor,
How would you divide the dataset into matrix of shape = [Batch_size, Timesteps, InputDimensions] ?

**Comment by ranjeetkumar** [comment]
Thanks all
