### ISSUE TITLE
activation function

### ISSUE THREAD

**Issue by ranjeetkumar** [iit-cs585/assignments#36]
In tensorflow, we have sigmoid activation function which is the standard form of logistic function.
https://www.tensorflow.org/versions/r0.10/api_docs/python/nn/activation_functions_
Can use this tf.sigmoid as a logistic function  in part 2 of the assignment? I am not seeing any other logistic function.  Also we can use any cell of rnn such as BasicLSTMCell  in the assignment?

**Comment by aronwc** [comment]
Yes, and yes.

**Comment by ranjeetkumar** [comment]
Thanks
