### ISSUE TITLE
How to save and load Model

### ISSUE THREAD

**Issue by nishug001** [iit-cs585/assignments#38]
Hi Professor,

I am trying to save word2vec model the first time and then load the save model to reduce running time. 
I am able to save the model via model.save('file_name) but Word2Vec.load(file_name) is showing error saying no attribute 'load'. 
Could you please guide me.

**Comment by Sihan0616** [comment]
Have you tried to use 'KeyedVectors.load_word2vec_format'?

For more information,check here:https://radimrehurek.com/gensim/models/word2vec.html
