### ISSUE TITLE
Clarification on is_valid_productions

### ISSUE THREAD

**Issue by mychandru024** [iit-cs585/assignments#4]
Respected Professor,
Should we also support to say that ('NP', ['Mary']) is a valid production wrt to rules as below?
rules = [('S', ['NP', 'VP']),
                 ('NP', ['ProperNoun']),
                 ('ProperNoun', ['John', 'Mary']),
                 ('VP', ['V', 'ProperNoun']),
                 ('V', ['likes', 'hates'])]

Thank you!

**Comment by aronwc** [comment]
No, it should only be direct productions.

**Comment by mychandru024** [comment]
Thank You Professor.
