### ISSUE TITLE
Extension of date of submission of bonus assignment

### ISSUE THREAD

**Issue by dporunne** [iit-cs585/assignments#42]
Hi Professor, Could you please extend the data of submission of bonus assignment?
This is because knowing about the various parameters and working of tensorflow and RNN  and integrating it with the given data is time consuming.

**Comment by chinmayeehota** [comment]
Hello Professor,

Kindly consider extending the deadline for only the bonus part. Thanks.

**Comment by SaiAyshwaryaLakshmi** [comment]
Hi Professor,
Please consider extending the deadline for bonus assignment, it is a bit difficult.
Thanks
