### ISSUE TITLE
test_is_pos()

### ISSUE THREAD

**Issue by nishug001** [iit-cs585/assignments#8]
rules = [('S', ['NP', 'VP']),
                 ('NP', ['ProperNoun']),
                 ('ProperNoun', ['John', 'Mary']),
                 ('VP', ['V', 'ProperNoun']),
                 ('V', ['likes', 'hates'])]

Should is_pos(('ProperNoun', ['XYZ',]), rules) return True or False as their is no production which leads for 'XYZ' ?

**Comment by nik-birur-472** [comment]
Returns True as '**XYZ**' doesn't appear as a LHS symbol in other rules.

**Comment by aronwc** [comment]
Yes.

**Comment by nishug001** [comment]
Thank you.
